### PR TITLE
Paper for JOSE in progress

### LINKED ISSUE #95: Prepare paper.md and paper.bib for JOSE submission
This lesson has been submitted to Carpentries lab for peer review: https://github.com/carpentries-lab/reviews/issues/24

To complete the review and be accepted for publication in JOSE, it will need paper.md and paper.bib files.
The requirements are described in
[instructions on learning module submission at JOSE](https://openjournals.readthedocs.io/en/jose/submitting.html#how-to-prepare-a-learning-module-submission)

We'll need to agree the author list first, see #93

### PR DESCRIPTION
**Pull request by ewallace**
This pull request, currently in draft, fixes #95. 

- [x] create paper.md file to be used for JOSE submission
- [x] add title, keywords, author list, acknowledgements
- [x] add ORCIDs for authors
- [x] draft summary following JOSE learning module guidelines
- [x] References as paper.bib, starting with the Good Enough Practices paper
- [x] Test that paper compiles using https://whedon.theoj.org/
- [x] Request reviews from co-authors.

### CODE REVIEW

**Review by emma-wilson — COMMENTED** [review]
The paper looks really good! I've created a pull request with some minor changes (capitalising words) #110

**Comment by emma-wilson** [comment]
Also can confirm that my author details are correct.

**Review by ameynert — APPROVED** [review]
I merged in a few edits and added a ref to the project organization and management for genomics lesson, which is a nice practical application of the principles taught here.

**Comment by ewallace** [comment]
@ameynert thank you, this looks great. Do you have funder information to add?

**Comment by ameynert** [comment]
> @ameynert thank you, this looks great. Do you have funder information to add?

Just the Ed-DaSH for this, I think.

**Pull request merged**
